#!/usr/bin/env bash
set -Eeuo pipefail

APP_NAME="airport-control-plane"
SERVICE_NAME="${APP_NAME}.service"
APP_USER="airport"
APP_GROUP="airport"
APP_DIR="/opt/airport-control-plane"
DATA_DIR="${APP_DIR}/data"
ENV_DIR="/etc/airport-control-plane"
ENV_FILE="${ENV_DIR}/airport.env"
LEGACY_ENV_FILE="${APP_DIR}/.env.production"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}"
NODE_MAJOR="${AIRPORT_NODE_MAJOR:-20}"
MEMORY_MAX="${AIRPORT_MEMORY_MAX:-256M}"
HEALTH_ATTEMPTS="${AIRPORT_HEALTH_ATTEMPTS:-40}"
HEALTH_DELAY_SECONDS="${AIRPORT_HEALTH_DELAY_SECONDS:-3}"
ROLLBACK_DIR=""
STAGING_DIR=""

usage() {
  cat <<'EOF'
Usage:
  sudo bash scripts/deploy-systemd.sh install
  sudo bash scripts/deploy-systemd.sh update

Canonical bare-metal systemd deployment for Ubuntu/Debian low-memory hosts.
Docker is intentionally not used by this script.
EOF
}

log() {
  printf '[deploy-systemd] %s\n' "$*"
}

fail() {
  printf '[deploy-systemd] ERROR: %s\n' "$*" >&2
  exit 1
}

cleanup() {
  if [ -n "$STAGING_DIR" ] && [ -d "$STAGING_DIR" ]; then
    rm -rf "$STAGING_DIR"
  fi
}
trap cleanup EXIT

random_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '\n' | tr '+/' 'AB' | cut -c1-32
    return
  fi

  dd if=/dev/urandom bs=24 count=1 2>/dev/null | base64 | tr -d '\n' | tr '+/' 'AB' | cut -c1-32
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    fail "请使用 root 或 sudo 执行。"
  fi
}

require_debian_or_ubuntu() {
  if [ ! -r /etc/os-release ]; then
    fail "无法识别系统；当前脚本只支持 Ubuntu/Debian。"
  fi

  # shellcheck disable=SC1091
  . /etc/os-release
  case " ${ID:-} ${ID_LIKE:-} " in
    *" debian "*|*" ubuntu "*) ;;
    *) fail "当前系统不是 Ubuntu/Debian family：${PRETTY_NAME:-unknown}" ;;
  esac
}

apt_install() {
  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y --no-install-recommends "$@"
}

node_major_version() {
  node -p 'Number(process.versions.node.split(".")[0])' 2>/dev/null || printf '0\n'
}

ensure_node_runtime() {
  local current_major
  current_major="$(node_major_version)"

  if [ "$current_major" -ge "$NODE_MAJOR" ] && command -v npm >/dev/null 2>&1; then
    log "Node.js $(node -v) / npm $(npm -v) 已满足要求。"
    return
  fi

  log "安装 Node.js ${NODE_MAJOR}.x 运行时。"
  apt-get update
  apt_install ca-certificates curl gnupg
  install -d -m 0755 /etc/apt/keyrings
  curl -fsSL "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key" \
    | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg.tmp
  mv /etc/apt/keyrings/nodesource.gpg.tmp /etc/apt/keyrings/nodesource.gpg
  chmod 0644 /etc/apt/keyrings/nodesource.gpg
  printf 'deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_%s.x nodistro main\n' "$NODE_MAJOR" \
    >/etc/apt/sources.list.d/nodesource.list
  apt-get update
  apt_install nodejs

  current_major="$(node_major_version)"
  if [ "$current_major" -lt "$NODE_MAJOR" ] || ! command -v npm >/dev/null 2>&1; then
    fail "Node.js 安装后仍不满足 >=${NODE_MAJOR}，请检查 apt 源。"
  fi
}

ensure_base_packages() {
  log "安装裸机部署所需基础包。"
  apt-get update
  apt_install ca-certificates curl git tar gzip coreutils systemd
  ensure_node_runtime
}

ensure_app_user() {
  if ! getent group "$APP_GROUP" >/dev/null 2>&1; then
    groupadd --system "$APP_GROUP"
  fi

  if ! id -u "$APP_USER" >/dev/null 2>&1; then
    useradd --system --gid "$APP_GROUP" --home-dir "$APP_DIR" --shell /usr/sbin/nologin "$APP_USER"
  fi
}

ensure_directories() {
  install -d -m 0755 "$APP_DIR"
  install -d -m 0750 -o "$APP_USER" -g "$APP_GROUP" "$DATA_DIR"
  install -d -m 0750 -o root -g "$APP_GROUP" "$ENV_DIR"
}

write_env_file_if_missing() {
  if [ -f "$ENV_FILE" ]; then
    return
  fi

  if [ -f "$LEGACY_ENV_FILE" ]; then
    install -m 0640 -o root -g "$APP_GROUP" "$LEGACY_ENV_FILE" "$ENV_FILE"
    log "已从现有裸机环境文件迁移配置：$LEGACY_ENV_FILE -> $ENV_FILE"
    return
  fi

  local auth_user="${CONTROL_PLANE_AUTH_USERNAME:-admin}"
  local auth_password="${CONTROL_PLANE_AUTH_PASSWORD:-$(random_password)}"

  umask 0077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/deploy-systemd.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
PORT=${PORT:-8080}
CONTROL_PLANE_AUTH_USERNAME=${auth_user}
CONTROL_PLANE_AUTH_PASSWORD=${auth_password}
CONTROL_PLANE_SESSION_TTL_MS=${CONTROL_PLANE_SESSION_TTL_MS:-43200000}
CONTROL_PLANE_SESSION_SECURE=${CONTROL_PLANE_SESSION_SECURE:-false}
CONTROL_PLANE_SESSION_REFRESH_PERSIST_INTERVAL_MS=${CONTROL_PLANE_SESSION_REFRESH_PERSIST_INTERVAL_MS:-30000}

PLATFORM_PUBLIC_BASE_URL=${PLATFORM_PUBLIC_BASE_URL:-}
CLIENT_PUBLIC_BASE_URL=${CLIENT_PUBLIC_BASE_URL:-}
NODE_SSH_USER=${NODE_SSH_USER:-root}
DEMO_SHELL_BINARY=${DEMO_SHELL_BINARY:-/bin/sh}
AIRPORT_ENABLE_LOCAL_DEMO_TRANSPORT=${AIRPORT_ENABLE_LOCAL_DEMO_TRANSPORT:-false}
OPERATION_EXECUTION_TIMEOUT_MS=${OPERATION_EXECUTION_TIMEOUT_MS:-300000}
OPERATION_OUTPUT_LIMIT_BYTES=${OPERATION_OUTPUT_LIMIT_BYTES:-128000}
OPERATION_TARGET_CONCURRENCY=${OPERATION_TARGET_CONCURRENCY:-3}
SSH_CONNECT_TIMEOUT_SECONDS=${SSH_CONNECT_TIMEOUT_SECONDS:-15}
PROBE_TCP_TIMEOUT_MS=${PROBE_TCP_TIMEOUT_MS:-4000}
PROBE_SSH_TIMEOUT_MS=${PROBE_SSH_TIMEOUT_MS:-12000}
AUTO_PROBE_ENABLED=${AUTO_PROBE_ENABLED:-true}
AUTO_PROBE_INTERVAL_MS=${AUTO_PROBE_INTERVAL_MS:-900000}
AUTO_PROBE_BATCH_SIZE=${AUTO_PROBE_BATCH_SIZE:-4}
AUTO_PROBE_MIN_GAP_MS=${AUTO_PROBE_MIN_GAP_MS:-600000}
AUTO_PROBE_JITTER_MS=${AUTO_PROBE_JITTER_MS:-10000}
TZ=${TZ:-Asia/Shanghai}
EOF
  chown root:"$APP_GROUP" "$ENV_FILE"
  chmod 0640 "$ENV_FILE"

  log "已生成环境文件：$ENV_FILE"
  log "初始登录账号：$auth_user"
  log "初始登录密码：$auth_password"
}

validate_env_file() {
  local auth_password
  auth_password="$(read_env_value CONTROL_PLANE_AUTH_PASSWORD)"

  if [ -z "$auth_password" ]; then
    fail "CONTROL_PLANE_AUTH_PASSWORD 不能为空。"
  fi

  if [ "$auth_password" = "CHANGE_ME" ]; then
    fail "CONTROL_PLANE_AUTH_PASSWORD 仍是 CHANGE_ME，请先改成强密码。"
  fi
}

read_env_value() {
  local key="$1"
  awk -F= -v key="$key" '
    $0 !~ /^[[:space:]]*(#|$)/ && $1 == key {
      sub(/^[^=]*=/, "", $0)
      print $0
      exit
    }
  ' "$ENV_FILE"
}

write_service_file() {
  cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=Airport Control Plane
Documentation=https://github.com/augus7737/airport-control-plane
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${APP_DIR}
Environment=NODE_ENV=production
EnvironmentFile=${ENV_FILE}
ExecStart=/usr/bin/node src/server.js
Restart=on-failure
RestartSec=5
TimeoutStartSec=30
TimeoutStopSec=30
KillSignal=SIGTERM
MemoryMax=${MEMORY_MAX}
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${DATA_DIR}
RestrictSUIDSGID=true
LockPersonality=true
CapabilityBoundingSet=
SystemCallArchitectures=native
UMask=0077

[Install]
WantedBy=multi-user.target
EOF
  chmod 0644 "$SERVICE_FILE"
  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME" >/dev/null
}

repo_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd
}

copy_repo_to_staging() {
  local root
  root="$(repo_root)"
  STAGING_DIR="$(mktemp -d /tmp/airport-control-plane.candidate.XXXXXX)"

  log "准备候选版本：$STAGING_DIR"
  (
    cd "$root"
    tar \
      --exclude='./.git' \
      --exclude='./node_modules' \
      --exclude='./data' \
      --exclude='./data-prod' \
      --exclude='./.env.production' \
      -cf - .
  ) | tar -xf - -C "$STAGING_DIR"

  chown -R "$APP_USER:$APP_GROUP" "$STAGING_DIR"
}

run_as_app_user() {
  runuser -u "$APP_USER" -- "$@"
}

install_candidate_dependencies() {
  log "安装生产依赖：npm ci --omit=dev"
  (
    cd "$STAGING_DIR"
    run_as_app_user npm ci --omit=dev
  )
}

test_candidate() {
  log "执行候选版本测试：npm test"
  (
    cd "$STAGING_DIR"
    run_as_app_user npm test
  )
}

safe_clean_app_dir() {
  if [ "$APP_DIR" != "/opt/airport-control-plane" ] || [ ! -d "$APP_DIR" ]; then
    fail "APP_DIR 安全校验失败：$APP_DIR"
  fi

  find "$APP_DIR" -mindepth 1 -maxdepth 1 \
    ! -name data \
    ! -name data-prod \
    ! -name .git \
    ! -name .env.production \
    -exec rm -rf {} +
}

create_rollback_backup() {
  if [ ! -d "$APP_DIR" ] || [ -z "$(find "$APP_DIR" -mindepth 1 -maxdepth 1 ! -name data ! -name data-prod ! -name .git ! -name .env.production -print -quit)" ]; then
    ROLLBACK_DIR=""
    return
  fi

  ROLLBACK_DIR="$(mktemp -d /opt/airport-control-plane.rollback.XXXXXX)"
  log "保存当前版本用于失败回滚：$ROLLBACK_DIR"
  (
    cd "$APP_DIR"
    tar \
      --exclude='./data' \
      --exclude='./data-prod' \
      --exclude='./.git' \
      --exclude='./.env.production' \
      -cf - .
  ) | tar -xf - -C "$ROLLBACK_DIR"
}

activate_candidate() {
  create_rollback_backup
  safe_clean_app_dir
  (
    cd "$STAGING_DIR"
    tar -cf - .
  ) | tar -xf - -C "$APP_DIR"
  find "$APP_DIR" -mindepth 1 -maxdepth 1 \
    ! -name .git \
    ! -name data-prod \
    ! -name .env.production \
    -exec chown -R "$APP_USER:$APP_GROUP" {} +
  chown -R "$APP_USER:$APP_GROUP" "$DATA_DIR"
}

service_port() {
  local port_value
  port_value="$(read_env_value PORT)"
  printf '%s\n' "${port_value:-8080}"
}

health_url() {
  printf 'http://127.0.0.1:%s/healthz\n' "$(service_port)"
}

print_recent_logs() {
  journalctl -u "$SERVICE_NAME" -n 120 --no-pager >&2 || true
}

wait_for_health() {
  local url attempt
  url="$(health_url)"
  log "等待服务健康就绪：$url"

  for attempt in $(seq 1 "$HEALTH_ATTEMPTS"); do
    if systemctl is-active --quiet "$SERVICE_NAME" && curl -fsS "$url" >/dev/null 2>&1; then
      log "服务已健康。"
      return 0
    fi

    if systemctl is-failed --quiet "$SERVICE_NAME"; then
      log "服务进入 failed 状态，最近日志如下：" >&2
      print_recent_logs
      return 1
    fi

    sleep "$HEALTH_DELAY_SECONDS"
  done

  log "服务未在预期时间内通过健康检查，最近日志如下：" >&2
  print_recent_logs
  return 1
}

rollback_activation() {
  if [ -z "$ROLLBACK_DIR" ] || [ ! -d "$ROLLBACK_DIR" ]; then
    log "没有可回滚版本；已停止未通过验证的服务。"
    systemctl stop "$SERVICE_NAME" >/dev/null 2>&1 || true
    return
  fi

  log "恢复上一版代码并重启服务。"
  safe_clean_app_dir
  (
    cd "$ROLLBACK_DIR"
    tar -cf - .
  ) | tar -xf - -C "$APP_DIR"
  find "$APP_DIR" -mindepth 1 -maxdepth 1 \
    ! -name .git \
    ! -name data-prod \
    ! -name .env.production \
    -exec chown -R "$APP_USER:$APP_GROUP" {} +
  chown -R "$APP_USER:$APP_GROUP" "$DATA_DIR"
  systemctl restart "$SERVICE_NAME" || true
  wait_for_health || true
}

restart_and_verify() {
  systemctl restart "$SERVICE_NAME"
  if ! wait_for_health; then
    rollback_activation
    fail "新版本未通过健康检查，部署失败。"
  fi
}

deploy() {
  require_root
  require_debian_or_ubuntu
  ensure_base_packages
  ensure_app_user
  ensure_directories
  write_env_file_if_missing
  validate_env_file
  write_service_file
  copy_repo_to_staging
  install_candidate_dependencies
  test_candidate
  activate_candidate
  restart_and_verify

  log "部署完成：$(health_url)"
  log "工作目录：$APP_DIR"
  log "环境文件：$ENV_FILE"
}

main() {
  local action="${1:-install}"
  case "$action" in
    install|update)
      deploy
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      usage >&2
      fail "未知动作：$action"
      ;;
  esac
}

main "$@"
