#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${AIRPORT_ENV_FILE:-$ROOT_DIR/.env.production}"
COMPOSE_FILE="$ROOT_DIR/compose.production.yml"
IMAGE_TAG_DEFAULT="airport-control-plane:latest"
CONTAINER_NAME_DEFAULT="airport-control-plane"

random_password() {
  openssl rand -base64 18 | tr -d '\n' | tr '+/' 'AB' | cut -c1-24
}

resolve_host_path() {
  local raw_path="$1"
  if [[ "$raw_path" = /* ]]; then
    printf '%s\n' "$raw_path"
    return
  fi

  printf '%s\n' "$ROOT_DIR/${raw_path#./}"
}

ensure_prerequisites() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "[deploy] 缺少 docker，请先安装 Docker。" >&2
    exit 1
  fi

  if ! command -v openssl >/dev/null 2>&1; then
    echo "[deploy] 缺少 openssl，无法生成默认登录密码。" >&2
    exit 1
  fi

  if ! docker info >/dev/null 2>&1; then
    echo "[deploy] Docker daemon 未运行，请先启动 Docker / Colima / Docker Desktop。" >&2
    exit 1
  fi
}

write_default_env_file() {
  local auth_user="${CONTROL_PLANE_AUTH_USERNAME:-admin}"
  local auth_password="${CONTROL_PLANE_AUTH_PASSWORD:-$(random_password)}"
  local host_port="${AIRPORT_HOST_PORT:-8080}"
  local bind_ip="${AIRPORT_BIND_IP:-0.0.0.0}"
  local data_dir="${AIRPORT_DATA_DIR:-./data-prod}"

  cat >"$ENV_FILE" <<EOF
# Generated by scripts/deploy-production.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AIRPORT_CONTAINER_NAME=${AIRPORT_CONTAINER_NAME:-$CONTAINER_NAME_DEFAULT}
AIRPORT_IMAGE_TAG=${AIRPORT_IMAGE_TAG:-$IMAGE_TAG_DEFAULT}
AIRPORT_BIND_IP=${bind_ip}
AIRPORT_HOST_PORT=${host_port}
AIRPORT_DATA_DIR=${data_dir}

CONTROL_PLANE_AUTH_USERNAME=${auth_user}
CONTROL_PLANE_AUTH_PASSWORD=${auth_password}
CONTROL_PLANE_SESSION_TTL_MS=${CONTROL_PLANE_SESSION_TTL_MS:-43200000}
CONTROL_PLANE_SESSION_SECURE=${CONTROL_PLANE_SESSION_SECURE:-false}

PLATFORM_PUBLIC_BASE_URL=${PLATFORM_PUBLIC_BASE_URL:-}
NODE_SSH_USER=${NODE_SSH_USER:-root}
DEMO_SHELL_BINARY=${DEMO_SHELL_BINARY:-/bin/sh}
OPERATION_EXECUTION_TIMEOUT_MS=${OPERATION_EXECUTION_TIMEOUT_MS:-300000}
SSH_CONNECT_TIMEOUT_SECONDS=${SSH_CONNECT_TIMEOUT_SECONDS:-15}
PROBE_TCP_TIMEOUT_MS=${PROBE_TCP_TIMEOUT_MS:-4000}
PROBE_SSH_TIMEOUT_MS=${PROBE_SSH_TIMEOUT_MS:-12000}
AUTO_PROBE_ENABLED=${AUTO_PROBE_ENABLED:-true}
AUTO_PROBE_INTERVAL_MS=${AUTO_PROBE_INTERVAL_MS:-900000}
AUTO_PROBE_BATCH_SIZE=${AUTO_PROBE_BATCH_SIZE:-4}
AUTO_PROBE_MIN_GAP_MS=${AUTO_PROBE_MIN_GAP_MS:-600000}
AUTO_PROBE_JITTER_MS=${AUTO_PROBE_JITTER_MS:-10000}
TZ=${TZ:-Asia/Shanghai}
EOF

  echo "[deploy] 已生成部署环境文件: $ENV_FILE"
  echo "[deploy] 登录账号: $auth_user"
  echo "[deploy] 登录密码: $auth_password"
  echo "[deploy] 如需绑定域名，请编辑 PLATFORM_PUBLIC_BASE_URL 后重新执行本脚本。"
}

load_env_file() {
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
}

detect_compose_cmd() {
  if docker compose version >/dev/null 2>&1; then
    printf 'docker compose'
    return 0
  fi

  if command -v docker-compose >/dev/null 2>&1; then
    printf 'docker-compose'
    return 0
  fi

  return 1
}

run_with_compose() {
  local compose_cmd="$1"
  echo "[deploy] 检测到 Compose，开始构建并启动容器..."
  if [[ "$compose_cmd" = "docker compose" ]]; then
    docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build
  else
    docker-compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build
  fi
}

run_with_plain_docker() {
  local data_dir_abs
  data_dir_abs="$(resolve_host_path "${AIRPORT_DATA_DIR:-./data-prod}")"
  mkdir -p "$data_dir_abs"

  echo "[deploy] 当前主机没有 Compose，切换到纯 docker 部署路径..."
  echo "[deploy] 构建镜像: ${AIRPORT_IMAGE_TAG:-$IMAGE_TAG_DEFAULT}"
  docker build -t "${AIRPORT_IMAGE_TAG:-$IMAGE_TAG_DEFAULT}" "$ROOT_DIR"

  if docker ps -a --format '{{.Names}}' | grep -Fxq "${AIRPORT_CONTAINER_NAME:-$CONTAINER_NAME_DEFAULT}"; then
    echo "[deploy] 检测到旧容器，先停止并删除..."
    docker rm -f "${AIRPORT_CONTAINER_NAME:-$CONTAINER_NAME_DEFAULT}" >/dev/null
  fi

  docker run -d \
    --name "${AIRPORT_CONTAINER_NAME:-$CONTAINER_NAME_DEFAULT}" \
    --restart unless-stopped \
    --init \
    --env-file "$ENV_FILE" \
    -e NODE_ENV=production \
    -e PORT=8080 \
    -p "${AIRPORT_BIND_IP:-0.0.0.0}:${AIRPORT_HOST_PORT:-8080}:8080" \
    -v "${data_dir_abs}:/app/data" \
    --health-cmd "curl -fsS http://127.0.0.1:8080/healthz >/dev/null || exit 1" \
    --health-interval 30s \
    --health-timeout 5s \
    --health-retries 3 \
    --health-start-period 20s \
    --security-opt no-new-privileges:true \
    --cap-drop ALL \
    "${AIRPORT_IMAGE_TAG:-$IMAGE_TAG_DEFAULT}" >/dev/null
}

print_summary() {
  local bind_ip="${AIRPORT_BIND_IP:-0.0.0.0}"
  local host_port="${AIRPORT_HOST_PORT:-8080}"
  local data_dir_abs
  data_dir_abs="$(resolve_host_path "${AIRPORT_DATA_DIR:-./data-prod}")"

  echo
  echo "[deploy] 部署完成"
  echo "[deploy] 访问地址: http://${bind_ip}:${host_port}"
  echo "[deploy] 数据目录: ${data_dir_abs}"
  echo "[deploy] 登录账号: ${CONTROL_PLANE_AUTH_USERNAME:-admin}"
  echo "[deploy] 如使用反向代理，请把 PLATFORM_PUBLIC_BASE_URL 改成正式域名并重新部署。"
}

main() {
  ensure_prerequisites

  if [[ ! -f "$ENV_FILE" ]]; then
    write_default_env_file
  fi

  load_env_file
  mkdir -p "$(resolve_host_path "${AIRPORT_DATA_DIR:-./data-prod}")"

  if compose_cmd="$(detect_compose_cmd)"; then
    run_with_compose "$compose_cmd"
  else
    run_with_plain_docker
  fi

  print_summary
}

main "$@"
